#ifndef VERSION_H
#define VERSION_H

#include "../SCMRevGen/scmrev.h"
#include <windows.h>

#define STRA(x) #x
#define STRW(x) L ## #x
#ifdef UNICODE
#define STR STRW
#else
#define STR STRA
#endif

#define STR_HELPERA(x) STRA(x)
#define STR_HELPERW(x) STRW(x)
#ifdef UNICODE
#define STR_HELPER STR_HELPERW
#else
#define STR_HELPER STR_HELPERA
#endif

#define SCYLLA_HIDE_VERSION_MAJOR 1
#define SCYLLA_HIDE_VERSION_MINOR 4
#define SCYLLA_HIDE_VERSION_PATCH GIT_VERSION_NUMBER

#define SCYLLA_HIDE_NAME_A "ScyllaHide"
#define SCYLLA_HIDE_NAME_W L"ScyllaHide"
#ifdef UNICODE
#define SCYLLA_HIDE_NAME SCYLLA_HIDE_NAME_W
#else
#define SCYLLA_HIDE_NAME SCYLLA_HIDE_NAME_A
#endif

#define SCYLLA_HIDE_VERSION_STRING_A STR_HELPERA(SCYLLA_HIDE_VERSION_MAJOR) "." STR_HELPERA(SCYLLA_HIDE_VERSION_MINOR) "." STR_HELPERA(SCYLLA_HIDE_VERSION_PATCH) "-" GIT_SHORT_HASH_A
#define SCYLLA_HIDE_VERSION_STRING_W STR_HELPERW(SCYLLA_HIDE_VERSION_MAJOR) L"." STR_HELPERW(SCYLLA_HIDE_VERSION_MINOR) L"." STR_HELPERW(SCYLLA_HIDE_VERSION_PATCH) L"-" GIT_SHORT_HASH_W
#ifdef UNICODE
#define SCYLLA_HIDE_VERSION_STRING SCYLLA_HIDE_VERSION_STRING_W
#else
#define SCYLLA_HIDE_VERSION_STRING SCYLLA_HIDE_VERSION_STRING_A
#endif

namespace scl {
	void ShowAboutBox(HWND hWnd);
}

#endif //VERSION_H
